apiVersion: v1
kind: Service
metadata:
  name: nimbus-site
  labels:
    app: nimbus-site
spec:
  type: LoadBalancer                 # AKS will allocate a public IP
  selector:
    app: nimbus-site
  ports:
    - name: http
      port: 80                       # service port
      targetPort: 80                 # container port
